FROM php:8.3-cli-alpine

COPY . /iyuu
WORKDIR /iyuu

# 安装php扩展可能没配置国内镜像，工具链和composer已经配置国内镜像，可能的话，需要拆分成基础镜像（php+扩展+composer本体）并定期构建基础镜像，然后在此基础上构建应用镜像（代码+composer依赖）
RUN curl -sSLf \
        -o /usr/local/bin/install-php-extensions \
        https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions && \
    chmod +x /usr/local/bin/install-php-extensions \

RUN sed -i 's/dl-cdn\.alpinelinux\.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && install-php-extensions pcntl gd xdebug curl fileinfo mbstring mysqli openssl pdo_mysql pdo_sqlite sqlite3 sockets sodium pcntl zip \
    && wget https://getcomposer.org/installer -O - -q | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
    && composer install

CMD ["php", "start.php", "start"]
